FROM chetansinghsajwan/cmake-dev AS base

ARG ZLIB_VERSION="1.3.1"
ARG PNG_VERSION="1.6.46"
ARG INSTALL_DIR="/out"

ENV CMAKE_GENERATOR="Ninja"

# -------------------------------------------------------------------------------------------------
# Install zlib, required by
# - png
# - freetype
# -------------------------------------------------------------------------------------------------

ARG TOOLCHAIN_LIST="l`inux-amd64 win-i686 win-amd64 win-armv7 win-aarch64"

FROM base AS zlib-builder

# foreach toolchain
RUN git clone "https://github.com/madler/zlib.git" . \
  --depth 1 --branch v$ZLIB_VERSION \
  && mkdir build \
  && cd build \
  && for TOOLCHAIN in $TOOLCHAIN_LIST; do \
  echo "Building for $TOOLCHAIN..." \
  && cmake .. \
  -D CMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_DIR/toolchain-$TOOLCHAIN.cmake \
  -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR/$TOOLCHAIN \
  && cmake --build . \
  && cmake --install . \
  && rm -rf * \
  ; done

# -------------------------------------------------------------------------------------------------
# Install png, required by
# - freetype
# - msdf-atlas-gen
# -------------------------------------------------------------------------------------------------

FROM base AS png-builder

COPY --from=zlib-builder $INSTALL_DIR /usr/local

RUN git clone "https://github.com/pnggroup/libpng.git" . \
  --depth 1 --branch v$PNG_VERSION \
  && mkdir build \
  && cd build \
  && for TOOLCHAIN in $TOOLCHAIN_LIST; do \
  echo "Building for $TOOLCHAIN..." \
  && cmake .. \
  -D CMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_DIR/toolchain-$TOOLCHAIN.cmake \
  -D PNG_STATIC=ON \
  -D PNG_SHARED=OFF \
  -D PNG_TESTS=OFF \
  && cmake --build . \
  && cmake --install . --prefix $INSTALL_DIR/$TOOLCHAIN \
  && rm -rf * \
  ; done
